# Generated by Django 3.1.7 on 2021-04-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naseem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='img',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='price',
        ),
    ]
